boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('<int:board_pk>/edit', views.update, name='update'),    
    path('<int:board_pk>/delete', views.delete, name='delete'),    
    path('<int:board_pk>/', views.detail, name='detail'),    
    path('new/', views.create, name='create'),    
    path('', views.index, name='index'),    
]

myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

boards/models.py
from django.db import models

# Create your models here.


class Board(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

boards/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Board

# class BoardForm(forms.Form):
#     title = forms.CharField(label='제목', widget=forms.TextInput(attrs={
#                                                     'placeholder': 'THE TITLE',
                                                       
#                                             }))
#     content = forms.CharField(label='내용', 
#                             error_messages={'required': '제발 내용을 입력해주세요!'},        
#                             widget=forms.Textarea(attrs={
#                                                     'class': 'Content-input',
#                                                     'rows': 5,
#                                                     'cols': 50,
#                                                     'placeholder': 'Fill the Content',
#                                             }))
    
class BoardForm(forms.ModelForm):
    # Model의 정보를 작성하는 곳
    class Meta:
        model = Board
        # models.py에 지정해놓은 필드를 사용한다.
        # fields, widget은 정해진 변수명
        fields = '__all__'
        widgets = {'title': forms.TextInput(attrs={
                                                'placeholder': '제목을 입력하세요.',
                                                'class': 'title'}),
                  'content': forms.Textarea(attrs={
                                                'placeholder': '내용을 입력하세요.',
                                                'class': 'content',
                                                'rows': 5,
                                                'cols': 50,})}
        error_messages = {'title': {
                                        'required': '제발 입력해주세요.'
                                    },
                          'content': {
                                        'required': '내용을 입력하지 않으면 죽는다.'
                                    },
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', '작성!'))
        

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board
from .forms import BoardForm

# Create your views here.

def index(request):
    boards = Board.objects.order_by('-pk')
    context = {
        'boards': boards
    }
    return render(request, 'boards/index.html', context)
    
# def create(request):
#     # POST 요청이면 FORM 데이터를 처리한다.
#     if request.method == 'POST':
#         # 이 처리과정은 "binding" 으로 불리는데, 폼의 유효성 체크를 할 수 있도록 해준다.
#         form = BoardForm(request.POST)
#         # form 유효성 체크 (안전한 데이터인지 체크)
#         if form.is_valid():
#             title = form.cleaned_data.get('title')
#             content = form.cleaned_data.get('content')
#             # 검증을 통과한 깨끗한 데이터를 form에서 가져와서 board를 만든다.
#             board = Board.objects.create(title=title, content=content)
#             return redirect('boards:detail', board.pk)
#     # GET 요청(혹은 다른 메서드)이면 기본 폼을 생성한다.
#     else:
#         form = BoardForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'boards/create.html', context)
    
def create(request):
    # POST 요청이면 FORM 데이터를 처리한다.
    if request.method == 'POST':
        # 이 처리과정은 "binding" 으로 불리는데, 폼의 유효성 체크를 할 수 있도록 해준다.
        form = BoardForm(request.POST)
        # form 유효성 체크 (안전한 데이터인지 체크)
        if form.is_valid():
            board = form.save()
            return redirect('boards:detail', board.pk)
    # GET 요청(혹은 다른 메서드)이면 기본 폼을 생성한다.
    else:
        form = BoardForm()
    context = {
        'form': form,
    }
    return render(request, 'boards/form.html', context)
        
def detail(request, board_pk):
    # board = Board.objects.get(pk=board_pk)
    board = get_object_or_404(Board, pk=board_pk)
    context = {
        'board':board
    }
    return render(request, 'boards/detail.html', context)
    
def delete(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')
    else:
        return redirect('boards:detail', board.pk)
    
# def update(request, board_pk):
#     board = get_object_or_404(Board, pk=board_pk)
#     if request.method == 'POST':
#         form = BoardForm(request.POST)
#         if form.is_valid():
#             board.title = form.cleaned_data.get('title')
#             board.content = form.cleaned_data.get('content')
#             board.save()
#             return redirect('boards:detail', board.pk)
#     # GET 요청이면(수정하기 버튼을 눌렀을 때)
#     else:
#         # BoardForm을 초기화(사용자 입력 값을 넣어준 상태로)
#         # form = BoardForm(initial={'title': board.title, 'content': board.content})
#         form = BoardForm(initial=board.__dict__)
#     # 1. POST : 요청에서 검증에 실패하였을 때, 오류 메세지가 포함된 상태로 넘어온다.
#     # 2. GET : 요청에서 초기화된 상태로 넘어온다.
#     context = {
#         'form': form,
#     }
#     return render(request, 'boards/create.html', context)
    
def update(request, board_pk):
    board = get_object_or_404(Board, pk=board_pk)
    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)    # 1
        if form.is_valid():                               
            board = form.save()                           # 2
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm(instance=board)                  # 3
    context = {
        'form': form,
        'board': board,
    }
    return render(request, 'boards/form.html', context)
        

boards/templates/boards/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <div class='container'>
        {% block body %} {% endblock %}
    </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

boards/templates/boards/detail.html
{% extends 'boards/base.html' %}
{% block body %}
<h1>{{ board.pk }}번째 글</h1>
<h2>{{ board.title }}</h2>
<hr>
<p>{{ board.content }}</p>
<a href="{% url 'boards:index' %}">BACK</a>
<form action="{% url 'boards:delete' board.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제"/>
</form>
<a href="{% url 'boards:update' board.pk %}">[수정]</a>
{% endblock %}

boards/templates/boards/form.html
{% extends 'boards/base.html' %}
{% block body %}
{% load crispy_forms_tags %}

{% if request.resolver_match.url_name == 'create' %}
    <h1>NEW board</h1>
{% else%}
    <h1>EDIT board</h1>
{% endif %}


<!-- 1 -->
<form method='POST'>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit"/>
</form>

<!-- 2 -->
<form method='POST'>
    {% csrf_token %}
    {{ form.title }}
    {{ form.content }}
    <input type="submit" value="Submit"/>
</form>

<!-- 3 -->
<form method='POST'>
    {% csrf_token %}
    {% for field in form %}
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    {% endfor %}
    <input type="submit" value="Submit"/>
</form>

<!-- 4 -->
{{ form.non_field_errors }}
<form method='POST'>
    {% csrf_token %}
    <div>
        {{ form.title.errors }}
        {{ form.title.label_tag }}
        {{ form.title }}
    </div>
    <div>
        {{ form.content.errors }}
        {{ form.content.label_tag }}
        {{ form.content }}
    </div>
    <input type="submit" value="Submit"/>
</form>

<!-- 5 -->
{% crispy form %}



{% if request.resolver_match.url_name == 'create' %}
    <a href="{% url 'boards:index' %}">BACK</a>
{% else%}
    <a href="{% url 'boards:detail' board.pk %}">BACK</a>
{% endif %}


{% endblock %}

boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% block body %}
<h1>게시글 목록</h1>
<a href="{% url 'boards:create' %}">[new]</a>
{% for board in boards %}
    <p>{{ board.pk }}</p>
    <p>{{ board.title }}</p>
    <a href="{% url 'boards:detail' board.pk %}">글 보러가기</a>
    <hr>
{% endfor %}
{% endblock %}